version: '3.7'
services:
  react-app:
    # for -it flag
    # stdin_open: true
    # tty: true
    # for development
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.dev
    image: atmanregistry.azurecr.io/frontend:20.09  #you can add a tag here
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    volumes:
      - ./src:/code/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env